/home/fs0/abaram/scripts/twoStep/fsl/preProcessData.sh 01
/home/fs0/abaram/scripts/twoStep/fsl/preProcessData.sh 02
/home/fs0/abaram/scripts/twoStep/fsl/preProcessData.sh 03
/home/fs0/abaram/scripts/twoStep/fsl/preProcessData.sh 04
/home/fs0/abaram/scripts/twoStep/fsl/preProcessData.sh 05
/home/fs0/abaram/scripts/twoStep/fsl/preProcessData.sh 06
/home/fs0/abaram/scripts/twoStep/fsl/preProcessData.sh 07
/home/fs0/abaram/scripts/twoStep/fsl/preProcessData.sh 08
/home/fs0/abaram/scripts/twoStep/fsl/preProcessData.sh 09
/home/fs0/abaram/scripts/twoStep/fsl/preProcessData.sh 10
/home/fs0/abaram/scripts/twoStep/fsl/preProcessData.sh 11
/home/fs0/abaram/scripts/twoStep/fsl/preProcessData.sh 12
/home/fs0/abaram/scripts/twoStep/fsl/preProcessData.sh 13
/home/fs0/abaram/scripts/twoStep/fsl/preProcessData.sh 14
